/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Otros.Conexion;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 *
 * @author David
 */
public class Menu extends javax.swing.JFrame {

    Conexion con;
    ResultSet rs;
    static JDialog contenedor = null;
    public static int idUsuario = 0;

    public Menu(String Username, int idUsuario) {
        initComponents();
        this.idUsuario = idUsuario;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        URL url = getClass().getResource("/images/icon.png");
        ImageIcon imgicon = new ImageIcon(url);
        this.setIconImage(imgicon.getImage());
        lblWelcome.setText("Bienvenido, "+Username+"!");
        con = new Conexion();
        con.Login();
        DeshabilitarBtn();
    }
    
    private void DeshabilitarBtn(){
        btnFindClientes.setEnabled(false);
        btnFindArticulos.setEnabled(false);
    }

    private Menu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFicha = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnCiudades = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMarcas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnArticulos = new javax.swing.JButton();
        btnFindFicha = new javax.swing.JButton();
        btnFindClientes = new javax.swing.JButton();
        btnFindArticulos = new javax.swing.JButton();
        btnIngresarStock = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOp = new javax.swing.JMenu();
        itemFicha = new javax.swing.JMenuItem();
        itemClientes = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemArticulos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuRef = new javax.swing.JMenu();
        itemCiudades = new javax.swing.JMenuItem();
        itemMarcas = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        itemChangelog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/id-card.png"))); // NOI18N
        btnFicha.setText("Ficha de Cliente");
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnCiudades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/city.png"))); // NOI18N
        btnCiudades.setText("Ciudades");
        btnCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadesActionPerformed(evt);
            }
        });

        jLabel1.setText("Configuración");

        btnMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/price-tag.png"))); // NOI18N
        btnMarcas.setText("Marcas");
        btnMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcasActionPerformed(evt);
            }
        });

        jLabel2.setText("Clientes/Pacientes");

        jLabel3.setText("Artículos");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btnExit.setText("Salir del Sistema");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblWelcome.setText("Bienvenido");

        btnArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delivery.png"))); // NOI18N
        btnArticulos.setText("Artículos");
        btnArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulosActionPerformed(evt);
            }
        });

        btnFindFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchlist.png"))); // NOI18N
        btnFindFicha.setText("Buscar Ficha/OT");
        btnFindFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFichaActionPerformed(evt);
            }
        });

        btnFindClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchlist.png"))); // NOI18N
        btnFindClientes.setText("Buscar Cliente");

        btnFindArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchlist.png"))); // NOI18N
        btnFindArticulos.setText("Consulta Artículos");
        btnFindArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindArticulosActionPerformed(evt);
            }
        });

        btnIngresarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addbox.png"))); // NOI18N
        btnIngresarStock.setText("Ingresar Stock");
        btnIngresarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarStockActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchlist.png"))); // NOI18N
        jButton1.setText("Resumen de Ventas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/complete.png"))); // NOI18N
        jButton2.setText("Métodos de Pago");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        menuOp.setText("Operaciones");

        itemFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/id-card.png"))); // NOI18N
        itemFicha.setText("Ficha de Cliente");
        itemFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFichaActionPerformed(evt);
            }
        });
        menuOp.add(itemFicha);

        itemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        itemClientes.setText("Clientes");
        itemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClientesActionPerformed(evt);
            }
        });
        menuOp.add(itemClientes);
        menuOp.add(jSeparator3);

        itemArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delivery.png"))); // NOI18N
        itemArticulos.setText("Artículos");
        itemArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArticulosActionPerformed(evt);
            }
        });
        menuOp.add(itemArticulos);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addbox.png"))); // NOI18N
        jMenuItem1.setText("Ingresar Stock");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuOp.add(jMenuItem1);

        jMenuBar1.add(menuOp);

        menuRef.setText("Referenciales");

        itemCiudades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/city.png"))); // NOI18N
        itemCiudades.setText("Ciudades");
        itemCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCiudadesActionPerformed(evt);
            }
        });
        menuRef.add(itemCiudades);

        itemMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/price-tag.png"))); // NOI18N
        itemMarcas.setText("Marcas");
        itemMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMarcasActionPerformed(evt);
            }
        });
        menuRef.add(itemMarcas);

        jMenuBar1.add(menuRef);

        menuHelp.setText("Ayuda");

        itemChangelog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gear.png"))); // NOI18N
        itemChangelog.setText("Changelog");
        itemChangelog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemChangelogActionPerformed(evt);
            }
        });
        menuHelp.add(itemChangelog);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFindFicha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFindClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIngresarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFindArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFicha)
                    .addComponent(btnClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindFicha)
                    .addComponent(btnFindClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArticulos)
                    .addComponent(btnIngresarStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFindArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCiudades)
                    .addComponent(btnMarcas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(lblWelcome))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcasActionPerformed
        contenedor = new JDialog();
        contenedor.getContentPane().add(new Marca());
        contenedor.setModal(true);
        contenedor.setTitle("Marcas");
        URL url = getClass().getResource("/images/icon.png");
        ImageIcon imgicon = new ImageIcon(url);
        contenedor.setIconImage(imgicon.getImage());
        contenedor.pack();
        contenedor.setLocationRelativeTo(null);
        contenedor.setResizable(false);
        contenedor.setVisible(true);
    }//GEN-LAST:event_btnMarcasActionPerformed

    private void itemMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMarcasActionPerformed
        contenedor = new JDialog();
        contenedor.getContentPane().add(new Marca());
        contenedor.setModal(true);
        contenedor.setTitle("Marcas");
        URL url = getClass().getResource("/images/icon.png");
        ImageIcon imgicon = new ImageIcon(url);
        contenedor.setIconImage(imgicon.getImage());
        contenedor.pack();
        contenedor.setLocationRelativeTo(null);
        contenedor.setResizable(false);
        contenedor.setVisible(true);
    }//GEN-LAST:event_itemMarcasActionPerformed

    private void btnCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadesActionPerformed
        contenedor = new JDialog();
        contenedor.getContentPane().add(new Ciudad());
        contenedor.setModal(true);
        contenedor.setTitle("Ciudades");
        URL url = getClass().getResource("/images/icon.png");
        ImageIcon imgicon = new ImageIcon(url);
        contenedor.setIconImage(imgicon.getImage());
        contenedor.pack();
        contenedor.setLocationRelativeTo(null);
        contenedor.setResizable(false);
        contenedor.setVisible(true);
    }//GEN-LAST:event_btnCiudadesActionPerformed

    private void itemCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCiudadesActionPerformed
        contenedor = new JDialog();
        contenedor.getContentPane().add(new Ciudad());
        contenedor.setModal(true);
        contenedor.setTitle("Ciudades");
        URL url = getClass().getResource("/images/icon.png");
        ImageIcon imgicon = new ImageIcon(url);
        contenedor.setIconImage(imgicon.getImage());
        contenedor.pack();
        contenedor.setLocationRelativeTo(null);
        contenedor.setResizable(false);
        contenedor.setVisible(true);
    }//GEN-LAST:event_itemCiudadesActionPerformed

    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        try {
            contenedor = new JDialog();
            contenedor.getContentPane().add(new Articulo());
            contenedor.setModal(true);
            contenedor.setTitle("Articulos");
            URL url = getClass().getResource("/images/boxicon.png");
            ImageIcon imgicon = new ImageIcon(url);
            contenedor.setIconImage(imgicon.getImage());
            contenedor.pack();
            contenedor.setLocationRelativeTo(null);
            contenedor.setResizable(false);
            contenedor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnFindArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindArticulosActionPerformed
        
    }//GEN-LAST:event_btnFindArticulosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        try {
            contenedor = new JDialog();
            contenedor.getContentPane().add(new Cliente());
            contenedor.setModal(true);
            contenedor.setTitle("Clientes");
            URL url = getClass().getResource("/images/usericon.png");
            ImageIcon imgicon = new ImageIcon(url);
            contenedor.setIconImage(imgicon.getImage());
            contenedor.pack();
            contenedor.setLocationRelativeTo(null);
            contenedor.setResizable(false);
            contenedor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
        try {
            contenedor = new JDialog();
            contenedor.getContentPane().add(new FichaCliente());
            contenedor.setModal(false);
            contenedor.setTitle("Ficha del Cliente");
            URL url = getClass().getResource("/images/idcardicon.png");
            ImageIcon imgicon = new ImageIcon(url);
            contenedor.setIconImage(imgicon.getImage());
            contenedor.pack();
            contenedor.setLocationRelativeTo(null);
            contenedor.setResizable(false);
            contenedor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFichaActionPerformed

    private void btnIngresarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarStockActionPerformed
        try {
            contenedor = new JDialog();
            contenedor.getContentPane().add(new Stock());
            contenedor.setModal(true);
            contenedor.setTitle("Ingresar Stock");
            URL url = getClass().getResource("/images/addicon.png");
            ImageIcon imgicon = new ImageIcon(url);
            contenedor.setIconImage(imgicon.getImage());
            contenedor.pack();
            contenedor.setLocationRelativeTo(null);
            contenedor.setResizable(false);
            contenedor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresarStockActionPerformed

    private void itemFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFichaActionPerformed
        btnFicha.doClick();
    }//GEN-LAST:event_itemFichaActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        btnClientes.doClick();
    }//GEN-LAST:event_itemClientesActionPerformed

    private void itemArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArticulosActionPerformed
        btnArticulos.doClick();
    }//GEN-LAST:event_itemArticulosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        btnIngresarStock.doClick();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnFindFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFichaActionPerformed
        contenedor = new JDialog();
        contenedor.getContentPane().add(new ListadoFicha());
        contenedor.setModal(false);
        contenedor.setTitle("Buscar Ficha");
        URL url = getClass().getResource("/images/searchicon.png");
        ImageIcon imgicon = new ImageIcon(url);
        contenedor.setIconImage(imgicon.getImage());
        contenedor.pack();
        contenedor.setLocationRelativeTo(null);
        contenedor.setResizable(false);
        contenedor.setVisible(true);
    }//GEN-LAST:event_btnFindFichaActionPerformed

    private void itemChangelogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemChangelogActionPerformed
        contenedor = new JDialog();
        contenedor.getContentPane().add(new Changelog());
        contenedor.setModal(false);
        contenedor.setTitle("Changelog (Registro de cambios)");
        URL url = getClass().getResource("/images/icon.png");
        ImageIcon imgicon = new ImageIcon(url);
        contenedor.setIconImage(imgicon.getImage());
        contenedor.pack();
        contenedor.setLocationRelativeTo(null);
        contenedor.setResizable(false);
        contenedor.setVisible(true);
    }//GEN-LAST:event_itemChangelogActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            contenedor = new JDialog();
            contenedor.getContentPane().add(new PayMethods());
            contenedor.setModal(true);
            contenedor.setTitle("Métodos de Pago");
            URL url = getClass().getResource("/images/icon.png");
            ImageIcon imgicon = new ImageIcon(url);
            contenedor.setIconImage(imgicon.getImage());
            contenedor.pack();
            contenedor.setLocationRelativeTo(null);
            contenedor.setResizable(false);
            contenedor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        contenedor = new JDialog();
        contenedor.getContentPane().add(new SalesSummary());
        contenedor.setModal(false);
        contenedor.setTitle("Resumen de Ventas");
        URL url = getClass().getResource("/images/searchicon.png");
        ImageIcon imgicon = new ImageIcon(url);
        contenedor.setIconImage(imgicon.getImage());
        contenedor.pack();
        contenedor.setLocationRelativeTo(null);
        contenedor.setResizable(false);
        contenedor.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnCiudades;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFicha;
    private javax.swing.JButton btnFindArticulos;
    private javax.swing.JButton btnFindClientes;
    private javax.swing.JButton btnFindFicha;
    private javax.swing.JButton btnIngresarStock;
    private javax.swing.JButton btnMarcas;
    private javax.swing.JMenuItem itemArticulos;
    private javax.swing.JMenuItem itemChangelog;
    private javax.swing.JMenuItem itemCiudades;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemFicha;
    private javax.swing.JMenuItem itemMarcas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuOp;
    private javax.swing.JMenu menuRef;
    // End of variables declaration//GEN-END:variables
}
